Mar 1041
uktrade/market-access-python-frontend pull request #209
Opened 2021-07-19 14:01 UTC by jamespacileo

2021-07-20 12:48 UTC, cad106uk requested changes
Why is there the empty file  templates/barriers/action_plans/edit_action_plan.html

2021-07-20 12:48 UTC, cad106uk commented on templates/barriers/action_plans/add_milestone.html
> +        <!-- <div id="{{ form.completion_date.name }}" class="{% form_group_classes form.completion_date.errors %}">
Delete commented out code.

2021-07-20 12:48 UTC, cad106uk commented on templates/barriers/action_plans/edit_milestone.html
> +        <!-- <div id="{{ form.completion_date.name }}" class="{% form_group_classes form.completion_date.errors %}">
delete not comment out

2021-08-03 12:37 UTC, jamespacileostint commented on templates/barriers/action_plans/edit_milestone.html
> +        <!-- <div id="{{ form.completion_date.name }}" class="{% form_group_classes form.completion_date.errors %}">
done

2021-08-03 12:38 UTC, jamespacileostint commented on templates/barriers/action_plans/add_milestone.html
> +        <!-- <div id="{{ form.completion_date.name }}" class="{% form_group_classes form.completion_date.errors %}">
done

2021-08-03 12:39 UTC, jamespacileostint commented on barriers/views/action_plans.py
> +        found = list(
done

2021-08-03 12:40 UTC, jamespacileostint commented on barriers/forms/action_plans.py
> +    # completion_date = MonthYearInFutureField(
removed

2021-08-03 12:41 UTC, jamespacileo commented on barriers/forms/action_plans.py
> +def get_action_type_category_form(action_type: str):
done

2021-08-03 12:43 UTC, jamespacileo commented on barriers/forms/action_plans.py
> +    def clean_assigned_to(self):
I agree could do with a mixin class I guess, bit burnt out thought eek

2021-08-03 13:18 UTC, cad106uk requested changes
There is a lot of duplicate code

2021-08-03 13:18 UTC, cad106uk commented on barriers/views/action_plans.py
> +    def get_form_kwargs(self):
This method should be in a super class

2021-08-03 13:18 UTC, cad106uk commented on barriers/views/action_plans.py
> +    def get_initial(self):
This method should be in a super class

2021-08-03 13:18 UTC, cad106uk commented on barriers/views/action_plans.py
> +    def get_success_url(self):
This method should be in a super class

2021-08-03 13:18 UTC, cad106uk commented on barriers/views/action_plans.py
> +    def get_success_url(self):
This method should be in a super class

2021-08-03 13:18 UTC, cad106uk commented on barriers/views/action_plans.py
> +    def get_form_kwargs(self):
This method should be in a super class

2021-08-03 13:18 UTC, cad106uk commented on barriers/views/action_plans.py
> +    def get_initial(self):
This method should be in a super class

2021-08-03 13:18 UTC, cad106uk commented on barriers/views/action_plans.py
> +    def get_success_url(self):
This method should be in a super class

2021-08-03 13:18 UTC, cad106uk commented on barriers/views/action_plans.py
> +    def get_form_kwargs(self):
This method should be in a super class

2021-08-03 13:18 UTC, cad106uk commented on barriers/views/action_plans.py
> +    def get_initial(self):
This method should be in a super class

2021-08-03 13:18 UTC, cad106uk commented on barriers/views/action_plans.py
> +    def get_success_url(self):
This method should be in a super class

2021-08-03 13:18 UTC, cad106uk commented on barriers/views/action_plans.py
> +    def get_success_url(self):
This method should be in a super class

2021-08-03 13:18 UTC, cad106uk commented on barriers/views/action_plans.py
> +    def get_success_url(self):
This method should be in a super class

2021-08-03 13:18 UTC, cad106uk commented on barriers/views/action_plans.py
> +    def get_success_url(self):
This method should be in a super class

2021-08-03 13:18 UTC, cad106uk commented on barriers/views/action_plans.py
> +    def get_success_url(self):
This method should be in a super class

2021-08-03 13:18 UTC, cad106uk commented on barriers/views/action_plans.py
> +    def get_success_url(self):
This method should be in a super class

2021-08-04 16:07 UTC, cad106uk approved these changes

2021-08-05 10:36 UTC, merged