MAR-1064 - Added webpack configuration mapping gulp
uktrade/market-access-python-frontend pull request #218
Opened 2021-09-08 11:23 UTC by jamespacileo

- Added a task on circle ci that should appear in the PR
- Added two separate concatenated webpack config files, one individually for the react as it needed bespoke output config

2021-09-08 11:31 UTC, kevincarrogan requested changes

2021-09-08 11:31 UTC, kevincarrogan commented on .circleci/config.yml
> +
I don't think this is actually doing anything is it? It's not being run as it's not in the workflows list below.

Is the intention of this to check that the build can run?

2021-09-08 16:15 UTC, jamespacileo commented on .circleci/config.yml
> +
fixed thanks for the correction, added the commands and install of node dependencies at the top of the tests task

2021-09-09 08:43 UTC, kevincarrogan approved these changes

2021-09-09 08:46 UTC, merged