Two additional CSAT questions
uktrade/market-access-python-frontend pull request #512
Opened 2023-09-18 17:21 UTC by ferozerub

2023-09-20 22:26 UTC, chris-pettinga requested changes

2023-09-20 22:26 UTC, chris-pettinga commented on templates/feedback.html
> +            {% if forloop.counter == 5 %}
I think we should check the value of the choice rather than the for counter, as if we add new choices it may get out of sync.

2023-09-20 22:26 UTC, chris-pettinga commented on templates/feedback.html
> +                            maxlength="1250">{% if form.other_detail.value %}{{ form.other_detail.value}}{% endif %}</textarea>
can use the built-in django template filter

```suggestion
                            maxlength="1250">{{ form.other_detail.value|default:''}}</textarea>
```

2023-09-20 22:26 UTC, chris-pettinga commented on barriers/forms/feedback.py
> +        elif not issues and csat_submission != "True":
I know this is not part of the PR but maybe we can think about changing the `csat_submission` field to include some custom logic to cast to a boolean, so we don't have to check for the string

2023-09-21 14:01 UTC, ferozerub commented on templates/feedback.html
> +                            maxlength="1250">{% if form.other_detail.value %}{{ form.other_detail.value}}{% endif %}</textarea>
Done

2023-09-25 08:39 UTC, chris-pettinga approved these changes

2023-09-25 11:16 UTC, merged