Allow Role Admin group to be assigned to users on test environments
uktrade/market-access-python-frontend pull request #553
Opened 2023-11-01 14:32 UTC by Santino-Trade

2023-11-02 10:10 UTC, chris-pettinga requested changes

2023-11-02 10:10 UTC, chris-pettinga commented on config/settings/dev.py
> +USER_ADDITIONAL_PERMISSION_GROUPS = [
can we append the 'Role Administrator' to this list rather than re-define it, in case we change the original list in base.py in the future and forget to make the changes here as well

2023-11-02 10:10 UTC, chris-pettinga commented on config/settings/local.py
> +USER_ADDITIONAL_PERMISSION_GROUPS = [
same as above

2023-11-02 10:10 UTC, chris-pettinga commented on config/settings/uat.py
> +USER_ADDITIONAL_PERMISSION_GROUPS = [
same as above

2023-11-02 10:23 UTC, Santino-Trade commented on config/settings/dev.py
> +USER_ADDITIONAL_PERMISSION_GROUPS = [
I think it would be better to extend the list in the specific environmnets rather than add more logic to the form definition to specifically remove the choice from the list when we're on prod (or adding it on other envs) - I can add a comment about it on the base settings file above the list there.

2023-11-03 11:38 UTC, chris-pettinga commented on config/settings/dev.py
> +USER_ADDITIONAL_PERMISSION_GROUPS = [
Agreed that we shouldn't pop the item from the list in prod (better to be explicit), but I think it would be cleaner to append here rather than completely redefine as there's lots of duplication. i.e. the base.py should have the bare minimum, whereas the dev/uat environments should have the additional. 

`USER_ADDITIONAL_PERMISSION_GROUPS.append("Role administrator")`

2023-11-03 11:39 UTC, abarolo commented on config/settings/base.py
>      "Download approved user",
Maybe we should define the set of permissions as an Enum in a constants/permissions file?

2023-11-06 11:02 UTC, chris-pettinga approved these changes

2023-11-06 11:24 UTC, Santino-Trade commented on config/settings/dev.py
> +USER_ADDITIONAL_PERMISSION_GROUPS = [
Added appends instead of overrides

2023-11-07 13:28 UTC, osimuka approved these changes

2023-11-07 15:05 UTC, merged